### ISSUE TITLE
Typo in the readme's config example...

### ISSUE THREAD

**Issue by jermdavis** [adoprog/Sitecore.ShipIt#4]
First off, thanks for doing the work of maintaining an update to Ship - I appreciate that.

I had a PR open on the original Ship repo for a typo in the readme, which could be rather confusing to new users. [There's a "." missing from the whitelist config](https://github.com/kevinobee/Sitecore.Ship/pull/80/commits/0e55d09ad1a5d6a8221aca48eace74fc32924b1e) which means whitelisting doesn't work if you happen to copy the readme example. The PR I put in was: https://github.com/kevinobee/Sitecore.Ship/pull/80

Any chance that typo fix could make its way into your repo, in order to avoid others suffering the confusion I did from that missing full stop? (I can re-do the PR on your repo if you'd like - but it seems simple enought that you might find it easier just to commit a fix...)

Thanks,
Jeremy

**Comment by adoprog** [comment]
@jermdavis Thanks! Fixed it!
